rfTestCov:
	g++ -g -fno-stack-protector main_covtype.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o cov.out

rfTestPhi:
	g++ -g -fno-stack-protector main_phi.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o phi.out

rfTestKDD:
	g++ -g -fno-stack-protector main_KDD.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o KDD.out

rfTestM5:
	g++ -g -fno-stack-protector main_M5.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o M5.out

rfTestElec:
	g++ -g -fno-stack-protector main_elec.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o elec.out

rfTestAWS:
	g++ -g -fno-stack-protector main_AWS.cpp incrementalDecisionTree.cpp Evaluation.cpp RF.cpp -o AWS.out

run:
	./*.out 0 0
	./*.out 0 0
	./*.out 0 0
	./*.out 0 0
	./*.out 0 0
	./*.out 0 0
	./*.out 0 1
	./*.out 0 1
	./*.out 0 1
	./*.out 0 1
	./*.out 0 1
	./*.out 0 1
	./*.out 1 0
	./*.out 1 0
	./*.out 1 0
	./*.out 1 0
	./*.out 1 0
	./*.out 1 0
	./*.out 1 1
	./*.out 1 1
	./*.out 1 1
	./*.out 1 1
	./*.out 1 1
	./*.out 1 1
	./*.out 1 2
	./*.out 1 2
	./*.out 1 2
	./*.out 1 2
	./*.out 1 2
	./*.out 1 2
	./*.out 1 3
	./*.out 1 3
	./*.out 1 3
	./*.out 1 3
	./*.out 1 3
	./*.out 1 3
	./*.out 1 4
	./*.out 1 4
	./*.out 1 4
	./*.out 1 4
	./*.out 1 4
	./*.out 1 4


runDT:
	./*.out 0
	./*.out 0
	./*.out 0
	./*.out 0
	./*.out 0
	./*.out 0
	./*.out 1
	./*.out 1
	./*.out 1
	./*.out 1
	./*.out 1
	./*.out 1
	./*.out 2
	./*.out 2
	./*.out 2
	./*.out 2
	./*.out 2
	./*.out 2
	./*.out 3
	./*.out 3
	./*.out 3
	./*.out 3
	./*.out 3
	./*.out 3
	./*.out 4
	./*.out 4
	./*.out 4
	./*.out 4
	./*.out 4
	./*.out 4


clear:
	rm ./*.out
