
alpha:0.1
beta:0.5
h:3

L1:2000?20
L2:2000?20
L3:2000?20
L4:2000?20
L5:2000?20
L6:2000?20
L7:2000?20
L8:2000?20
L9:2000?20
L10:2000?20
L11:2000?20
L12:2000?20
L13:2000?20
L14:2000?20
L15:2000?20
L16:2000?20
L17:2000?20
L18:2000?20
L19:2000?20
L20:2000?20
L21:2000?20
L22:2000?20
L23:2000?20
L24:2000?20
L25:2000?20
L26:2000?20
L27:2000?20
L28:2000?20
L29:2000?20
L30:2000?20
L31:2000?20
L32:2000?20
L33:2000?20
L34:2000?20
L35:2000?20
L36:2000?20
L37:2000?20
L38:2000?20
L39:2000?20
L40:2000?20
L41:2000?20
L42:2000?20
L43:2000?20
L44:2000?20
L45:2000?20
L46:2000?20
L47:2000?20
L48:2000?20
L49:2000?20
L50:2000?20
L51:2000?20
L52:2000?20
L53:2000?20
L54:2000?20
L55:2000?20
L56:2000?20
L57:2000?20
L58:2000?20
L59:2000?20
L60:2000?20
L61:2000?20
L62:2000?20
L63:2000?20
L64:2000?20
L65:2000?20
L66:2000?20
L67:2000?20
L68:2000?20
L69:2000?20
L70:2000?20
L71:2000?20
L72:2000?20
L73:2000?20
L74:2000?20
L75:2000?20
L76:2000?20
L77:2000?20
L78:2000?20
L79:2000?20
L80:2000?20
L81:2000?20
L82:2000?20
L83:2000?20
L84:2000?20
L85:2000?20
L86:2000?20
L87:2000?20
L88:2000?20
L89:2000?20
L90:2000?20
L91:2000?20
L92:2000?20
L93:2000?20
L94:2000?20
L95:2000?20
L96:2000?20
L97:2000?20
L98:2000?20
L99:2000?20
L100:2000?20
L101:2000?20
L102:2000?20
L103:2000?20
L104:2000?20
L105:2000?20
L106:2000?20
L107:2000?20
L108:2000?20
L109:2000?20
L110:2000?20
L111:2000?20
L112:2000?20
L113:2000?20
L114:2000?20
L115:2000?20
L116:2000?20
L117:2000?20
L118:2000?20
L119:2000?20
L120:2000?20
L121:2000?20
L122:2000?20
L123:2000?20
L124:2000?20
L125:2000?20
L126:2000?20
L127:2000?20
L128:2000?20
L129:2000?20
L130:2000?20
L131:2000?20
L132:2000?20
L133:2000?20
L134:2000?20
L135:2000?20
L136:2000?20
L137:2000?20
L138:2000?20
L139:2000?20
L140:2000?20
L141:2000?20
L142:2000?20
L143:2000?20
L144:2000?20
L145:2000?20
L146:2000?20
L147:2000?20
L148:2000?20
L149:2000?20
L150:2000?20
L151:2000?20
L152:2000?20
L153:2000?20
L154:2000?20
L155:2000?20
L156:2000?20
L157:2000?20
L158:2000?20
L159:2000?20
L160:2000?20
L161:2000?20
L162:2000?20
L163:2000?20
L164:2000?20
L165:2000?20
L166:2000?20
L167:2000?20
L168:2000?20
L169:2000?20
L170:2000?20
L171:2000?20
L172:2000?20
L173:2000?20
L174:2000?20
L175:2000?20
L176:2000?20
L177:2000?20
L178:2000?20
L179:2000?20
L180:2000?20
L181:2000?20
L182:2000?20
L183:2000?20
L184:2000?20
L185:2000?20
L186:2000?20
L187:2000?20
L188:2000?20
L189:2000?20
L190:2000?20
L191:2000?20
L192:2000?20
L193:2000?20
L194:2000?20
L195:2000?20
L196:2000?20
L197:2000?20
L198:2000?20
L199:2000?20
L200:2000?20
L201:2000?20
L202:2000?20
L203:2000?20
L204:2000?20
L205:2000?20
L206:2000?20
L207:2000?20
L208:2000?20
L209:2000?20
L210:2000?20
L211:2000?20
L212:2000?20
L213:2000?20
L214:2000?20
L215:2000?20
L216:2000?20
L217:2000?20
L218:2000?20
L219:2000?20
L220:2000?20
L221:2000?20
L222:2000?20
L223:2000?20
L224:2000?20
L225:2000?20
L226:2000?20
L227:2000?20
L228:2000?20
L229:2000?20
L230:2000?20
L231:2000?20
L232:2000?20
L233:2000?20
L234:2000?20
L235:2000?20
L236:2000?20
L237:2000?20
L238:2000?20
L239:2000?20
L240:2000?20
L241:2000?20
L242:2000?20
L243:2000?20
L244:2000?20
L245:2000?20
L246:2000?20
L247:2000?20
L248:2000?20
L249:2000?20
L250:2000?20
L251:2000?20
L252:2000?20
L253:2000?20
L254:2000?20
L255:2000?20
L256:2000?20
L257:2000?20
L258:2000?20
L259:2000?20
L260:2000?20
L261:2000?20
L262:2000?20
L263:2000?20
L264:2000?20
L265:2000?20
L266:2000?20
L267:2000?20
L268:2000?20
L269:2000?20
L270:2000?20
L271:2000?20
L272:2000?20
L273:2000?20
L274:2000?20
L275:2000?20
L276:2000?20
L277:2000?20
L278:2000?20
L279:2000?20
L280:2000?20
L281:2000?20
L282:2000?20
L283:2000?20
L284:2000?20
L285:2000?20
L286:2000?20
L287:2000?20
L288:2000?20
L289:2000?20
L290:2000?20
L291:2000?20
L292:2000?20
L293:2000?20
L294:2000?20
L295:2000?20
L296:2000?20
L297:2000?20
L298:2000?20
L299:2000?20
L300:2000?20
L301:2000?20
L302:2000?20
L303:2000?20
L304:2000?20
L305:2000?20
L306:2000?20
L307:2000?20
L308:2000?20
L309:2000?20
L310:2000?20
L311:2000?20
L312:2000?20
L313:2000?20
L314:2000?20
L315:2000?20
L316:2000?20
L317:2000?20
L318:2000?20
L319:2000?20
L320:2000?20
L321:2000?20
L322:2000?20
L323:2000?20
L324:2000?20
L325:2000?20
L326:2000?20
L327:2000?20
L328:2000?20
L329:2000?20
L330:2000?20
L331:2000?20
L332:2000?20
L333:2000?20
L334:2000?20
L335:2000?20
L336:2000?20
L337:2000?20
L338:2000?20
L339:2000?20
L340:2000?20
L341:2000?20
L342:2000?20
L343:2000?20
L344:2000?20
L345:2000?20
L346:2000?20
L347:2000?20
L348:2000?20
L349:2000?20
L350:2000?20
L351:2000?20
L352:2000?20
L353:2000?20
L354:2000?20
L355:2000?20
L356:2000?20
L357:2000?20
L358:2000?20
L359:2000?20
L360:2000?20
L361:2000?20
L362:2000?20
L363:2000?20
L364:2000?20
L365:2000?20
L366:2000?20
L367:2000?20
L368:2000?20
L369:2000?20
L370:2000?20
L371:2000?20
L372:2000?20
L373:2000?20
L374:2000?20
L375:2000?20
L376:2000?20
L377:2000?20
L378:2000?20
L379:2000?20
L380:2000?20
L381:2000?20
L382:2000?20
L383:2000?20
L384:2000?20
L385:2000?20
L386:2000?20
L387:2000?20
L388:2000?20
L389:2000?20
L390:2000?20
L391:2000?20
L392:2000?20
L393:2000?20
L394:2000?20
L395:2000?20
L396:2000?20
L397:2000?20
L398:2000?20
L399:2000?20
L400:2000?20
L401:2000?20
L402:2000?20
L403:2000?20
L404:2000?20
L405:2000?20
L406:2000?20
L407:2000?20
L408:2000?20
L409:2000?20
L410:2000?20
L411:2000?20
L412:2000?20
L413:2000?20
L414:2000?20
L415:2000?20
L416:2000?20
L417:2000?20
L418:2000?20
L419:2000?20
L420:2000?20
L421:2000?20
L422:2000?20
L423:2000?20
L424:2000?20
L425:2000?20
L426:2000?20
L427:2000?20
L428:2000?20
L429:2000?20
L430:2000?20
L431:2000?20
L432:2000?20
L433:2000?20
L434:2000?20
L435:2000?20
L436:2000?20
L437:2000?20
L438:2000?20
L439:2000?20
L440:2000?20
L441:2000?20
L442:2000?20
L443:2000?20
L444:2000?20
L445:2000?20
L446:2000?20
L447:2000?20
L448:2000?20
L449:2000?20
L450:2000?20
L451:2000?20
L452:2000?20
L453:2000?20
L454:2000?20
L455:2000?20
L456:2000?20
L457:2000?20
L458:2000?20
L459:2000?20
L460:2000?20
L461:2000?20
L462:2000?20
L463:2000?20
L464:2000?20
L465:2000?20
L466:2000?20
L467:2000?20
L468:2000?20
L469:2000?20
L470:2000?20
L471:2000?20
L472:2000?20
L473:2000?20
L474:2000?20
L475:2000?20
L476:2000?20
L477:2000?20
L478:2000?20
L479:2000?20
L480:2000?20
L481:2000?20
L482:2000?20
L483:2000?20
L484:2000?20
L485:2000?20
L486:2000?20
L487:2000?20
L488:2000?20
L489:2000?20
L490:2000?20
L491:2000?20
L492:2000?20
L493:2000?20
L494:2000?20
L495:2000?20
L496:2000?20
L497:2000?20
L498:2000?20
L499:2000?20
L500:2000?20

t1:.z.t

p:()
p:p,1.
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:p,(p[(#p)-1]*(1-alpha))
p:|p
l:()
m:0
newL:()
h1:beta*(h-1)
a1:beta%alpha
ax:a1
l:l,L1
newL:L1
m:l[0] /only appears on first time
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L2
newL:L2
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L3
newL:L3
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L4
newL:L4
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L5
newL:L5
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L6
newL:L6
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L7
newL:L7
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L8
newL:L8
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L9
newL:L9
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L10
newL:L10
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L11
newL:L11
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L12
newL:L12
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L13
newL:L13
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L14
newL:L14
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L15
newL:L15
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L16
newL:L16
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L17
newL:L17
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L18
newL:L18
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L19
newL:L19
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L20
newL:L20
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L21
newL:L21
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L22
newL:L22
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L23
newL:L23
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L24
newL:L24
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L25
newL:L25
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L26
newL:L26
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L27
newL:L27
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L28
newL:L28
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L29
newL:L29
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L30
newL:L30
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L31
newL:L31
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L32
newL:L32
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L33
newL:L33
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L34
newL:L34
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L35
newL:L35
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L36
newL:L36
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L37
newL:L37
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L38
newL:L38
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L39
newL:L39
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L40
newL:L40
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L41
newL:L41
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L42
newL:L42
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L43
newL:L43
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L44
newL:L44
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L45
newL:L45
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L46
newL:L46
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L47
newL:L47
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L48
newL:L48
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L49
newL:L49
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L50
newL:L50
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L51
newL:L51
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L52
newL:L52
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L53
newL:L53
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L54
newL:L54
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L55
newL:L55
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L56
newL:L56
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L57
newL:L57
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L58
newL:L58
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L59
newL:L59
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L60
newL:L60
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L61
newL:L61
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L62
newL:L62
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L63
newL:L63
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L64
newL:L64
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L65
newL:L65
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L66
newL:L66
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L67
newL:L67
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L68
newL:L68
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L69
newL:L69
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L70
newL:L70
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L71
newL:L71
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L72
newL:L72
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L73
newL:L73
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L74
newL:L74
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L75
newL:L75
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L76
newL:L76
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L77
newL:L77
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L78
newL:L78
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L79
newL:L79
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L80
newL:L80
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L81
newL:L81
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L82
newL:L82
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L83
newL:L83
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L84
newL:L84
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L85
newL:L85
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L86
newL:L86
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L87
newL:L87
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L88
newL:L88
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L89
newL:L89
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L90
newL:L90
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L91
newL:L91
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L92
newL:L92
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L93
newL:L93
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L94
newL:L94
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L95
newL:L95
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L96
newL:L96
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L97
newL:L97
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L98
newL:L98
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L99
newL:L99
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L100
newL:L100
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L101
newL:L101
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L102
newL:L102
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L103
newL:L103
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L104
newL:L104
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L105
newL:L105
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L106
newL:L106
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L107
newL:L107
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L108
newL:L108
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L109
newL:L109
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L110
newL:L110
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L111
newL:L111
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L112
newL:L112
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L113
newL:L113
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L114
newL:L114
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L115
newL:L115
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L116
newL:L116
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L117
newL:L117
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L118
newL:L118
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L119
newL:L119
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L120
newL:L120
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L121
newL:L121
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L122
newL:L122
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L123
newL:L123
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L124
newL:L124
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L125
newL:L125
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L126
newL:L126
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L127
newL:L127
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L128
newL:L128
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L129
newL:L129
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L130
newL:L130
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L131
newL:L131
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L132
newL:L132
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L133
newL:L133
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L134
newL:L134
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L135
newL:L135
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L136
newL:L136
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L137
newL:L137
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L138
newL:L138
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L139
newL:L139
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L140
newL:L140
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L141
newL:L141
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L142
newL:L142
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L143
newL:L143
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L144
newL:L144
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L145
newL:L145
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L146
newL:L146
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L147
newL:L147
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L148
newL:L148
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L149
newL:L149
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L150
newL:L150
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L151
newL:L151
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L152
newL:L152
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L153
newL:L153
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L154
newL:L154
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L155
newL:L155
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L156
newL:L156
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L157
newL:L157
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L158
newL:L158
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L159
newL:L159
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L160
newL:L160
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L161
newL:L161
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L162
newL:L162
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L163
newL:L163
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L164
newL:L164
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L165
newL:L165
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L166
newL:L166
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L167
newL:L167
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L168
newL:L168
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L169
newL:L169
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L170
newL:L170
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L171
newL:L171
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L172
newL:L172
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L173
newL:L173
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L174
newL:L174
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L175
newL:L175
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L176
newL:L176
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L177
newL:L177
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L178
newL:L178
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L179
newL:L179
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L180
newL:L180
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L181
newL:L181
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L182
newL:L182
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L183
newL:L183
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L184
newL:L184
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L185
newL:L185
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L186
newL:L186
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L187
newL:L187
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L188
newL:L188
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L189
newL:L189
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L190
newL:L190
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L191
newL:L191
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L192
newL:L192
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L193
newL:L193
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L194
newL:L194
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L195
newL:L195
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L196
newL:L196
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L197
newL:L197
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L198
newL:L198
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L199
newL:L199
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L200
newL:L200
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L201
newL:L201
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L202
newL:L202
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L203
newL:L203
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L204
newL:L204
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L205
newL:L205
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L206
newL:L206
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L207
newL:L207
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L208
newL:L208
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L209
newL:L209
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L210
newL:L210
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L211
newL:L211
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L212
newL:L212
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L213
newL:L213
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L214
newL:L214
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L215
newL:L215
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L216
newL:L216
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L217
newL:L217
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L218
newL:L218
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L219
newL:L219
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L220
newL:L220
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L221
newL:L221
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L222
newL:L222
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L223
newL:L223
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L224
newL:L224
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L225
newL:L225
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L226
newL:L226
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L227
newL:L227
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L228
newL:L228
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L229
newL:L229
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L230
newL:L230
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L231
newL:L231
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L232
newL:L232
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L233
newL:L233
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L234
newL:L234
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L235
newL:L235
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L236
newL:L236
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L237
newL:L237
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L238
newL:L238
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L239
newL:L239
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L240
newL:L240
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L241
newL:L241
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L242
newL:L242
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L243
newL:L243
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L244
newL:L244
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L245
newL:L245
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L246
newL:L246
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L247
newL:L247
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L248
newL:L248
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L249
newL:L249
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L250
newL:L250
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L251
newL:L251
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L252
newL:L252
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L253
newL:L253
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L254
newL:L254
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L255
newL:L255
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L256
newL:L256
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L257
newL:L257
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L258
newL:L258
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L259
newL:L259
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L260
newL:L260
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L261
newL:L261
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L262
newL:L262
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L263
newL:L263
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L264
newL:L264
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L265
newL:L265
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L266
newL:L266
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L267
newL:L267
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L268
newL:L268
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L269
newL:L269
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L270
newL:L270
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L271
newL:L271
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L272
newL:L272
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L273
newL:L273
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L274
newL:L274
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L275
newL:L275
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L276
newL:L276
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L277
newL:L277
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L278
newL:L278
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L279
newL:L279
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L280
newL:L280
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L281
newL:L281
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L282
newL:L282
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L283
newL:L283
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L284
newL:L284
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L285
newL:L285
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L286
newL:L286
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L287
newL:L287
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L288
newL:L288
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L289
newL:L289
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L290
newL:L290
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L291
newL:L291
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L292
newL:L292
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L293
newL:L293
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L294
newL:L294
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L295
newL:L295
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L296
newL:L296
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L297
newL:L297
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L298
newL:L298
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L299
newL:L299
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L300
newL:L300
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L301
newL:L301
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L302
newL:L302
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L303
newL:L303
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L304
newL:L304
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L305
newL:L305
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L306
newL:L306
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L307
newL:L307
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L308
newL:L308
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L309
newL:L309
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L310
newL:L310
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L311
newL:L311
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L312
newL:L312
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L313
newL:L313
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L314
newL:L314
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L315
newL:L315
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L316
newL:L316
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L317
newL:L317
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L318
newL:L318
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L319
newL:L319
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L320
newL:L320
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L321
newL:L321
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L322
newL:L322
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L323
newL:L323
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L324
newL:L324
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L325
newL:L325
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L326
newL:L326
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L327
newL:L327
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L328
newL:L328
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L329
newL:L329
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L330
newL:L330
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L331
newL:L331
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L332
newL:L332
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L333
newL:L333
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L334
newL:L334
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L335
newL:L335
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L336
newL:L336
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L337
newL:L337
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L338
newL:L338
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L339
newL:L339
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L340
newL:L340
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L341
newL:L341
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L342
newL:L342
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L343
newL:L343
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L344
newL:L344
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L345
newL:L345
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L346
newL:L346
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L347
newL:L347
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L348
newL:L348
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L349
newL:L349
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L350
newL:L350
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L351
newL:L351
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L352
newL:L352
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L353
newL:L353
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L354
newL:L354
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L355
newL:L355
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L356
newL:L356
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L357
newL:L357
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L358
newL:L358
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L359
newL:L359
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L360
newL:L360
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L361
newL:L361
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L362
newL:L362
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L363
newL:L363
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L364
newL:L364
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L365
newL:L365
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L366
newL:L366
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L367
newL:L367
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L368
newL:L368
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L369
newL:L369
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L370
newL:L370
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L371
newL:L371
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L372
newL:L372
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L373
newL:L373
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L374
newL:L374
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L375
newL:L375
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L376
newL:L376
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L377
newL:L377
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L378
newL:L378
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L379
newL:L379
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L380
newL:L380
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L381
newL:L381
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L382
newL:L382
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L383
newL:L383
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L384
newL:L384
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L385
newL:L385
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L386
newL:L386
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L387
newL:L387
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L388
newL:L388
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L389
newL:L389
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L390
newL:L390
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L391
newL:L391
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L392
newL:L392
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L393
newL:L393
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L394
newL:L394
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L395
newL:L395
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L396
newL:L396
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L397
newL:L397
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L398
newL:L398
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L399
newL:L399
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L400
newL:L400
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L401
newL:L401
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L402
newL:L402
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L403
newL:L403
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L404
newL:L404
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L405
newL:L405
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L406
newL:L406
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L407
newL:L407
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L408
newL:L408
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L409
newL:L409
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L410
newL:L410
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L411
newL:L411
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L412
newL:L412
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L413
newL:L413
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L414
newL:L414
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L415
newL:L415
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L416
newL:L416
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L417
newL:L417
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L418
newL:L418
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L419
newL:L419
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L420
newL:L420
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L421
newL:L421
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L422
newL:L422
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L423
newL:L423
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L424
newL:L424
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L425
newL:L425
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L426
newL:L426
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L427
newL:L427
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L428
newL:L428
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L429
newL:L429
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L430
newL:L430
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L431
newL:L431
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L432
newL:L432
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L433
newL:L433
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L434
newL:L434
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L435
newL:L435
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L436
newL:L436
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L437
newL:L437
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L438
newL:L438
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L439
newL:L439
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L440
newL:L440
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L441
newL:L441
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L442
newL:L442
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L443
newL:L443
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L444
newL:L444
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L445
newL:L445
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L446
newL:L446
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L447
newL:L447
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L448
newL:L448
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L449
newL:L449
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L450
newL:L450
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L451
newL:L451
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L452
newL:L452
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L453
newL:L453
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L454
newL:L454
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L455
newL:L455
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L456
newL:L456
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L457
newL:L457
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L458
newL:L458
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L459
newL:L459
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L460
newL:L460
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L461
newL:L461
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L462
newL:L462
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L463
newL:L463
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L464
newL:L464
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L465
newL:L465
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L466
newL:L466
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L467
newL:L467
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L468
newL:L468
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L469
newL:L469
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L470
newL:L470
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L471
newL:L471
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L472
newL:L472
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L473
newL:L473
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L474
newL:L474
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L475
newL:L475
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L476
newL:L476
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L477
newL:L477
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L478
newL:L478
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L479
newL:L479
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L480
newL:L480
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L481
newL:L481
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L482
newL:L482
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L483
newL:L483
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L484
newL:L484
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L485
newL:L485
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L486
newL:L486
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L487
newL:L487
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L488
newL:L488
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L489
newL:L489
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L490
newL:L490
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L491
newL:L491
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L492
newL:L492
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L493
newL:L493
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L494
newL:L494
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L495
newL:L495
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L496
newL:L496
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L497
newL:L497
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L498
newL:L498
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L499
newL:L499
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

l:l,L500
newL:L500
an:(1-alpha)*p[0]
tmp:0
ax:ax*an
m:(alpha*(sum (p*newL)))+(an*m)
predict:((m + h1 + a1) - ax)

t2:.z.t

t2-t1