runIRF:
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 

runPhi:
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3

runKDD:
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 1
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 2
	python3 HoeffdingTree.py KDD 3
	python3 HoeffdingTree.py KDD 3
	python3 HoeffdingTree.py KDD 3
	python3 HoeffdingTree.py KDD 3
	python3 HoeffdingTree.py KDD 3
	python3 HoeffdingTree.py KDD 3

runElec:
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3

runAWS:
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 1
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 2
	python3 HoeffdingTree.py AWS 3
	python3 HoeffdingTree.py AWS 3
	python3 HoeffdingTree.py AWS 3
	python3 HoeffdingTree.py AWS 3
	python3 HoeffdingTree.py AWS 3
	python3 HoeffdingTree.py AWS 3

runM5:
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
