runIRF:
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 

runCov:
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3

runSynth:
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 1
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 2 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 

runPhi:
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3

runElec:
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3

runM5:
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3

runTmp2:
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3


runTmp:
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
	python3 HoeffdingTree.py Synth 3 
