default:
	python3 HoeffdingTree.py covtype 4
	python3 HoeffdingTree.py covtype 4
	python3 HoeffdingTree.py covtype 4
	python3 HoeffdingTree.py covtype 4
	python3 HoeffdingTree.py covtype 4

runIRF:
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 
	python irfTest.py 20 

runCov:
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 1
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 2
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3
	python3 HoeffdingTree.py covtype 3

runGradual:
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 1 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 2 0
	python3 HoeffdingTree.py Synth 3 0
	python3 HoeffdingTree.py Synth 3 0
	python3 HoeffdingTree.py Synth 3 0
	python3 HoeffdingTree.py Synth 3 0
	python3 HoeffdingTree.py Synth 3 0
	python3 HoeffdingTree.py Synth 3 0

runAbrupto:
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 1 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 2 1
	python3 HoeffdingTree.py Synth 3 1
	python3 HoeffdingTree.py Synth 3 1
	python3 HoeffdingTree.py Synth 3 1
	python3 HoeffdingTree.py Synth 3 1
	python3 HoeffdingTree.py Synth 3 1
	python3 HoeffdingTree.py Synth 3 1

runPhi:
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 1
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 2
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3
	python3 HoeffdingTree.py phi 3

runElec:
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 1
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 2
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3
	python3 HoeffdingTree.py Elec 3

runM5:
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 1
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 2
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
	python3 HoeffdingTree.py M5 3
